from enum import StrEnum


class ApplicantType(StrEnum):
    DOMESTIC = "DOMESTIC"
    INTERNATIONAL = "INTERNATIONAL"
    UNKNOWN = "UNKNOWN"


class ConfidenceLevel(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class RuleSeverity(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class RuleDomain(StrEnum):
    ACADEMIC = "ACADEMIC"
    ACTIVITY = "ACTIVITY"
    APPLICATION = "APPLICATION"
    COLLEGE = "COLLEGE"
    DATA = "DATA"
    ESSAY = "ESSAY"
    FINANCIAL = "FINANCIAL"
    HONOR = "HONOR"
    LOR = "LOR"
    PRIVACY = "PRIVACY"
    TEST = "TEST"
    WEB = "WEB"


class EvaluationStatus(StrEnum):
    COMPLETE = "COMPLETE"
    INCOMPLETE = "INCOMPLETE"
    REQUIREMENT_INCOMPLETE = "REQUIREMENT_INCOMPLETE"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class TestPolicy(StrEnum):
    REQUIRED = "REQUIRED"
    OPTIONAL = "OPTIONAL"
    FLEXIBLE = "FLEXIBLE"
    BLIND = "BLIND"
    NOT_ACCEPTED = "NOT_ACCEPTED"
    PROGRAM_DEPENDENT = "PROGRAM_DEPENDENT"
    OPTIONAL_FOR_INTL_OUTSIDE_US = "OPTIONAL_FOR_INTL_OUTSIDE_US"
    OPTIONAL_WITH_PROGRAM_EXCEPTIONS = "OPTIONAL_WITH_PROGRAM_EXCEPTIONS"
    UNKNOWN = "UNKNOWN"


class NeedPolicy(StrEnum):
    NEED_BLIND = "NEED_BLIND"
    NEED_AWARE = "NEED_AWARE"
    NO_NEED_BASED_AID = "NO_NEED_BASED_AID"
    LIMITED = "LIMITED"
    LIMITED_NEED_BASED = "LIMITED_NEED_BASED"
    MERIT_FOCUSED_LIMITED = "MERIT_FOCUSED_LIMITED"
    NEED_AWARE_OR_SELECTIVE = "NEED_AWARE_OR_SELECTIVE"
    NO_NEED_BASED_AID_OR_VERY_LIMITED = "NO_NEED_BASED_AID_OR_VERY_LIMITED"
    MERIT_AND_LIMITED_GRANTS = "MERIT_AND_LIMITED_GRANTS"
    MERIT_FOCUSED = "MERIT_FOCUSED"
    MERIT_ONLY = "MERIT_ONLY"
    MERIT_ONLY_LIMITED = "MERIT_ONLY_LIMITED"
    MERIT_ONLY_OR_LIMITED = "MERIT_ONLY_OR_LIMITED"
    MERIT_ONLY_WITH_CANADIAN_EXCEPTION = "MERIT_ONLY_WITH_CANADIAN_EXCEPTION"
    MERIT_OR_LIMITED = "MERIT_OR_LIMITED"
    MERIT_SCHOLARSHIPS = "MERIT_SCHOLARSHIPS"
    NEED_AWARE_LIMITED = "NEED_AWARE_LIMITED"
    NEED_AWARE_NO_NEED_AID = "NEED_AWARE_NO_NEED_AID"
    NEED_BASED_AVAILABLE = "NEED_BASED_AVAILABLE"
    NEED_BLIND_ADMISSION_NO_NEED_AID = "NEED_BLIND_ADMISSION_NO_NEED_AID"
    NO_SCHOLARSHIPS_FOR_INTL_UNDERGRAD = "NO_SCHOLARSHIPS_FOR_INTL_UNDERGRAD"
    SCHOLARSHIP_AVAILABLE = "SCHOLARSHIP_AVAILABLE"
    UNKNOWN = "UNKNOWN"


class RequirementStatus(StrEnum):
    REQUIRED = "REQUIRED"
    OPTIONAL = "OPTIONAL"
    RECOMMENDED = "RECOMMENDED"
    NOT_REQUIRED = "NOT_REQUIRED"
    UNKNOWN = "UNKNOWN"


class CompletionStatus(StrEnum):
    MISSING = "MISSING"
    PRESENT = "PRESENT"
    SUBMITTED = "SUBMITTED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    NOT_EVALUATED = "NOT_EVALUATED"


class PlanningCategory(StrEnum):
    HIGH_REACH = "HIGH_REACH"
    REACH = "REACH"
    COMPETITIVE = "COMPETITIVE"
    LIKELY_ISH = "LIKELY_ISH"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class DataFreshness(StrEnum):
    CURRENT = "CURRENT"
    REVIEW_SOON = "REVIEW_SOON"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"
