"use client";

import { useCallback, useEffect, useState } from "react";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Checkbox, Input } from "@/components/ui/field";
import { apiError, authenticatedFetch } from "@/lib/api/client";

interface Course { id: string; course_name: string; subject_area: string | null; course_level: string | null; grade_value: string | null; grade_text: string | null; is_advanced: boolean | null; is_highest_available: boolean | null; is_major_related: boolean | null; term_id: string | null }
export function CourseEditor({ profileId }: { profileId: string }) {
  const [courses, setCourses] = useState<Course[]>([]);
  const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await authenticatedFetch(`/api/v1/profiles/${profileId}/courses`); if (!response.ok) throw new Error(await apiError(response)); setCourses(((await response.json()) as { data: Course[] }).data); }, [profileId]);
  useEffect(() => { void (async () => { try { await load(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Unable to load courses."); } })(); }, [load]);
  function writable(items: Course[]) { return items.map((item) => { const copy: Partial<Course> = { ...item }; delete copy.id; return copy as Omit<Course, "id">; }); }
  async function replace(items: Omit<Course, "id">[]) { const response = await authenticatedFetch(`/api/v1/profiles/${profileId}/courses`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(items) }); if (!response.ok) throw new Error(await apiError(response)); await load(); }
  async function save(form: FormData) { setMessage(null); try { await replace([...writable(courses), { term_id: null, course_name: String(form.get("course_name") ?? "").trim(), subject_area: String(form.get("subject_area") ?? "").trim() || null, course_level: String(form.get("course_level") ?? "").trim() || null, grade_value: String(form.get("grade_value") ?? "").trim() || null, grade_text: String(form.get("grade_text") ?? "").trim() || null, is_advanced: form.get("is_advanced") === "on", is_highest_available: form.get("is_highest_available") === "on", is_major_related: form.get("is_major_related") === "on" }]); setMessage("Course saved."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Unable to save course."); } }
  async function remove(id: string) { try { await replace(writable(courses.filter((course) => course.id !== id))); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Unable to remove course."); } }
  return <Card className="mt-8 p-6"><h2 className="text-xl font-bold">Course detail</h2><p className="mt-2 text-sm text-muted">Optional details support rigor and major-preparation evidence.</p><form action={save} className="mt-5 grid gap-5"><div className="grid gap-5 sm:grid-cols-2"><Input id="course-name" label="Course name" name="course_name" required /><Input id="subject-area" label="Core subject area" name="subject_area" placeholder="Math, Science, English…" /><Input id="course-level" label="Course level" name="course_level" placeholder="Standard, Honors, IB HL…" /><Input id="course-grade" label="Numeric grade" name="grade_value" type="number" step="0.001" /><Input id="course-grade-text" label="Grade text" name="grade_text" placeholder="A, 7, Distinction…" /></div><div className="grid gap-3 sm:grid-cols-3"><Checkbox id="course-advanced" label="Advanced course" name="is_advanced" /><Checkbox id="course-highest" label="Highest available level" name="is_highest_available" /><Checkbox id="course-major" label="Related to intended major" name="is_major_related" /></div>{message ? <Alert title="Course status">{message}</Alert> : null}<div className="flex justify-end"><Button type="submit">Add course</Button></div></form>{courses.length ? <ul className="mt-5 grid gap-2">{courses.map((course) => <li className="flex items-center justify-between gap-3 rounded-lg border border-border p-3" key={course.id}><span><strong>{course.course_name}</strong><span className="ml-2 text-sm text-muted">{[course.subject_area, course.course_level].filter(Boolean).join(" · ")}</span></span><Button onClick={() => void remove(course.id)} variant="danger">Remove</Button></li>)}</ul> : null}</Card>;
}
