import { notFound } from "next/navigation";
import { Card } from "@/components/ui/card";
import { StatusBadge } from "@/components/ui/status-badge";

const methods: Record<string, { title: string; version: string; measured: string; limits: string }> = {
  academic: { title: "Academic Strength", version: "academic-1.1.0", measured: "Normalized school-scale performance, OLS trend, rigor across five canonical core areas relative to available courses, context, and major preparation.", limits: "No forced US GPA conversion and no prediction of admission." },
  activities: { title: "Activity Portfolio", version: "activity-1.1.0", measured: "Evidence-backed impact, responsibility, duration, initiative, time, recognition, progression, and portfolio concentration.", limits: "Founder titles require concrete responsibility evidence; titles and activity count alone do not raise a score." },
  honors: { title: "Honor Evaluation", version: "honor-1.1.0", measured: "Scope, documented selectivity, placement, major-linked academic relevance, and recurrence.", limits: "Unknown scope stays unknown; prestige is not inferred from a name." },
  essay: { title: "Mechanical Essay Score", version: "essay-1.0.0", measured: "Compliance, clarity, structure, text-based specificity and reflection signals, variety, and style hygiene.", limits: "Does not measure authenticity, emotion, personality, or reviewer reaction." },
  "writing-patterns": { title: "Writing Pattern Risk", version: "writing-patterns-1.0.0", measured: "Twenty-five deterministic checks across rhythm, detail, language, perspective, repetition, and sentence patterns. Each result exposes its observed metric and threshold.", limits: "Does not identify AI authorship, human authorship, intent, originality, or admission quality. Short samples reduce confidence and may leave checks unavailable." },
  "essay-ideas": { title: "Essay Idea Builder", version: "idea-builder-1.0.0", measured: "Stable combinations of user-provided moments, tensions, values, changes, and optional people or places.", limits: "Does not invent experiences, rank ideas, assess admission value, or generate finished essay prose." },
  gpa: { title: "GPA Toolkit", version: "gpa-calculator-1.0.0", measured: "Credit-weighted US letter-grade points or weight-adjusted grades on a user-defined international scale. US weighting is applied only through an explicitly selected method.", limits: "There is no universal weighted-GPA scale. International grades remain on their original scale; this tool does not silently convert them to a US 4.0 GPA." },
  coursework: { title: "Coursework Rigor", version: "coursework-1.0.0", measured: "Challenge against explicitly reported school offerings, five-area core coverage, advanced-opportunity utilization, progression across grade levels, and preparation for the intended major.", limits: "School offerings are never inferred from country. A school with no advanced opportunities receives the documented neutral-context score; course labels and counts alone do not establish rigor." },
  lor: { title: "Recommendation Signals", version: "lor-1.0.0", measured: "Relationship context, concrete examples, comparative language, specificity, and support signals.", limits: "Does not infer recommender intent or applicant character beyond the text." },
  "lor-builder": { title: "Recommendation Framework Builder", version: "lor-builder-1.0.0", measured: "Deterministic placement of user-supplied relationship context, observed qualities, examples, comparative evidence, and selected endorsement strength into an editable five-part framework.", limits: "Does not invent anecdotes, awards, rankings, qualities, or relationship details. Sentence shells retain explicit placeholders, and the recommender must own the final wording." },
  college: { title: "College Evaluation", version: "college-1.1.0", measured: "Academic alignment, CDS-weighted application strength, requirements, financial fit, institution-level selectivity, and source confidence.", limits: "CDS mappings are internal product weights. Unknown factors are excluded and reduce confidence. No acceptance probability, guarantee, or safety label." },
  testing: { title: "Testing Context", version: "academic-1.1.0", measured: "Reported test scores are compared only with published college ranges and the college's current test policy.", limits: "A test score is not interpreted as an admission probability and test-optional choices are not penalized by default." },
  application: { title: "Application Audit", version: "application-1.1.0", measured: "Required and optional material completion, explicit evaluation date, deadlines, and separate quality-evaluation status.", limits: "Completeness never substitutes for material quality; missing college requirements are treated as insufficient data." },
};

export default async function ComponentMethodologyPage({ params }: { params: Promise<{ component: string }> }) {
  const method = methods[(await params).component];
  if (!method) notFound();
  return <div className="mx-auto w-full max-w-3xl px-5 py-12 sm:px-8"><p className="text-sm font-semibold text-primary">Methodology</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><h1 className="text-4xl font-bold tracking-tight">{method.title}</h1><StatusBadge tone="info">{method.version}</StatusBadge></div><Card className="mt-8 p-6 sm:p-8"><h2 className="font-semibold">What is measured</h2><p className="mt-2 leading-7 text-muted">{method.measured}</p><h2 className="mt-7 font-semibold">Limits</h2><p className="mt-2 leading-7 text-muted">{method.limits}</p><p className="mt-7 text-sm text-muted">Same input + same data snapshot + same versions = same result.</p></Card></div>;
}
