"use client";

import { useEffect, useState } from "react";
import { Alert } from "@/components/ui/alert";
import { Button, ButtonLink } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Select } from "@/components/ui/field";
import { StatusBadge } from "@/components/ui/status-badge";
import { apiError, authenticatedFetch } from "@/lib/api/client";

interface Profile { id: string }
interface Checklist { requirement_type: string; required: boolean; completion_status: string; deadline: string | null; quality_status: string }
interface Audit { completeness_score: number; readiness: string; missing_required: string[]; critical_issues: string[]; priorities: string[]; checklist: Checklist[] }

export function ApplicationAudit({ collegeId }: { collegeId: string }) {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [audit, setAudit] = useState<Audit | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  useEffect(() => { authenticatedFetch("/api/v1/profiles").then(async (response) => { if (!response.ok) throw new Error(await apiError(response)); setProfile(((await response.json()) as { data: Profile[] }).data[0] ?? null); }).catch((reason: unknown) => setMessage(reason instanceof Error ? reason.message : "Unable to load profile.")); }, []);
  async function runAudit() { if (!profile) return; setBusy(true); setMessage(null); try { const response = await authenticatedFetch(`/api/v1/profiles/${profile.id}/colleges/${encodeURIComponent(collegeId)}/audit`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ evaluation_date: new Date().toISOString().slice(0, 10) }) }); if (!response.ok) throw new Error(await apiError(response)); setAudit(((await response.json()) as { data: { audit: Audit } }).data.audit); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Audit failed."); } finally { setBusy(false); } }
  async function save(form: FormData) { if (!profile || !audit) return; setBusy(true); setMessage(null); try { const materials = audit.checklist.map((item, index) => ({ requirement_type: item.requirement_type, completion_status: form.get(`status-${index}`), linked_entity_id: null, notes: null })); const response = await authenticatedFetch(`/api/v1/profiles/${profile.id}/colleges/${encodeURIComponent(collegeId)}/materials`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(materials) }); if (!response.ok) throw new Error(await apiError(response)); setMessage("Material status saved. Run the audit again to refresh readiness."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Unable to save checklist."); } finally { setBusy(false); } }
  return <>{message ? <Alert className="mt-8" title="Application status">{message}</Alert> : null}{!profile ? <Alert className="mt-8" title="Profile needed" tone="warning">Create a profile first.</Alert> : <div className="mt-8 flex flex-wrap gap-3"><Button disabled={busy} onClick={() => void runAudit()}>{busy ? "Checking…" : audit ? "Run audit again" : "Run application audit"}</Button><ButtonLink href="/methodology/application" variant="secondary">Why this audit?</ButtonLink></div>}{audit ? <><div className="mt-6 grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-sm text-muted">Completeness</p><p className="mt-2 text-3xl font-bold">{Math.round(audit.completeness_score)}%</p></Card><Card className="p-5"><p className="text-sm text-muted">Readiness</p><p className="mt-2 text-xl font-bold">{audit.readiness}</p></Card><Card className="p-5"><p className="text-sm text-muted">Missing required</p><p className="mt-2 text-3xl font-bold">{audit.missing_required.length}</p></Card></div>{audit.priorities.length ? <Alert className="mt-5" title="Prioritized actions" tone="danger"><ol className="list-decimal pl-5">{audit.priorities.map((issue) => <li key={issue}>{issue}</li>)}</ol></Alert> : null}<Card className="mt-5 p-6"><h2 className="text-xl font-bold">Material checklist</h2><p className="mt-2 text-sm text-muted">Completeness and quality are intentionally separate.</p><form action={save} className="mt-5 grid gap-4">{audit.checklist.map((item, index) => <div className="grid gap-3 rounded-lg border border-border p-4 sm:grid-cols-[1fr_auto] sm:items-end" key={`${item.requirement_type}-${index}`}><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{item.requirement_type}</h3><StatusBadge tone={item.required ? "warning" : "neutral"}>{item.required ? "REQUIRED" : "OPTIONAL"}</StatusBadge></div><p className="mt-1 text-sm text-muted">{item.deadline ? `Deadline ${new Date(item.deadline).toLocaleDateString()}` : "No deadline published"} · Quality {item.quality_status === "EVALUATED" ? "evaluated" : "not evaluated"}</p></div><Select id={`status-${index}`} label="Completion" name={`status-${index}`} defaultValue={item.completion_status}><option value="MISSING">Missing</option><option value="PRESENT">Present</option><option value="SUBMITTED">Submitted</option><option value="NOT_APPLICABLE">Not applicable</option><option value="NOT_EVALUATED">Not evaluated</option></Select></div>)}<div className="flex justify-end"><Button disabled={busy} type="submit">Save checklist</Button></div></form></Card></> : null}</>;
}
